
language: generic
sudo: false

branches:
  only:
    - master

before_install:
 - git clone https://github.com/nasfarley88/habash
 - git config --global user.email "lujun9972@gmail.com"
 - git config --global user.name "darksun"
 
script:
- ./habash/habash up "翻译Emacs文档"
- echo -e $TRAVIS_PRIVATE >~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
- wc -l ~/.ssh/id_rsa
- echo "Host github.com" >> ~/.ssh/config
- echo "   Hostname github.com" >> ~/.ssh/config
- echo "   StrictHostKeyChecking no" >> ~/.ssh/config
- echo "   CheckHostIP no" >> ~/.ssh/config
- echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
- git clone git@github.com:lujun9972/emacs-document.git
- cd emacs-document && ./generate_index.sh >README.org
- git commit -a -m "update README" || exit 0
- git push origin master
