
language: generic
sudo: false

branches:
  only:
    - master

before_install:
 - git clone https://github.com/nasfarley88/habash
 - git clone https://github.com/lujun9972/emacs-document
 - git config --global user.email "lujun9972@gmail.com"
 - git config --global user.name "darksun"
 
script:
- ./habash/habash up "翻译Emacs文档"
- echo $TRAVIS_PRIVATE >~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
- cd emacs-document && ./generate_index.sh >README.org && git commit -a -m "update README" && git push origin master
