
language: generic
sudo: false

branches:
  only:
    - master

before_install:
 - git clone https://github.com/nasfarley88/habash
 - git clone git@github.com:lujun9972/emacs-document.git --depth 1
 - git config --global user.email "lujun9972@gmail.com"
 - git config --global user.name "darksun"
 
script:
- ./habash/habash up "翻译Emacs文档"
- echo -e $TRAVIS_PRIVATE >~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
- echo "Host git.coding.net" >> ~/.ssh/config
- echo "   Hostname git.coding.net" >> ~/.ssh/config
- echo "   StrictHostKeyChecking no" >> ~/.ssh/config
- echo "   CheckHostIP no" >> ~/.ssh/config
- echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
- cd emacs-document && ./generate_index.sh >README.org && git commit -a -m "update README" && git push origin master
